// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../database/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTrackedLocation(location: $models.LocationPayload): $CancellablePromise<void> {
  return $Call.ByID(4197385228, location);
}

export function DeleteTrackedLocation(id: number): $CancellablePromise<void> {
  return $Call.ByID(3887965460, id);
}

export function GetHomeLocation(): $CancellablePromise<models$0.UserLocation> {
  return $Call.ByID(2858098212);
}

export function GetTrackedLocation(): $CancellablePromise<models$0.UserLocation[] | null> {
  return $Call.ByID(2400967417);
}

export function SearchLocation(
  name: string,
  limit: number,
): $CancellablePromise<models$0.LocationSearchResult[] | null> {
  return $Call.ByID(2046908579, name, limit);
}

export function UpsertHomeLocation(location: $models.LocationPayload): $CancellablePromise<void> {
  return $Call.ByID(826004439, location);
}
