// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LocationPayload {
  city_id: number | null;
  state_id: number | null;
  country_id: number;
  timezone_id: number;
  city: string | null;
  state: string | null;
  country: string;
  country_flag: string;
  timezone: string;
}
