// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../database/models/models.js";

export function GetTimeFormat(): $CancellablePromise<models$0.TimeFormat> {
  return $Call.ByID(3395987181);
}

export function UpdateTimeFormat(timeFormat: string): $CancellablePromise<void> {
  return $Call.ByID(783690602, timeFormat);
}
