// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum LocationScope {
  /**
   * The Go zero value for the underlying type of the enum.
   */
  $zero = "",

  LocationScopeCity = "city",
  LocationScopeState = "state",
  LocationScopeCountry = "country",
}

export interface LocationSearchResult {
  id: number;
  city_id: number | null;
  state_id: number | null;
  country_id: number;
  timezone_id: number | null;
  city: string | null;
  state: string | null;
  country: string;
  country_flag: string;
  timezone: string | null;
  name: string;
  type: SearchType;
  timezone_count: number;
}

export enum LocationType {
  /**
   * The Go zero value for the underlying type of the enum.
   */
  $zero = "",

  LocationTypeHome = "home",
  LocationTypeTracked = "tracked",
}

export enum SearchType {
  /**
   * The Go zero value for the underlying type of the enum.
   */
  $zero = "",

  SearchTypeCountry = "country",
  SearchTypeState = "state",
  SearchTypeCity = "city",
}

export enum TimeFormat {
  /**
   * The Go zero value for the underlying type of the enum.
   */
  $zero = "",

  TimeFormat12Hour = "12hr",
  TimeFormat24Hour = "24hr",
}

export interface UserLocation {
  id: number;
  type: LocationType;
  scope: LocationScope;
  city_id: number | null;
  state_id: number | null;
  country_id: number;
  timezone_id: number;
  city: string | null;
  state: string | null;
  country: string;
  country_flag: string;
  timezone: string;
  created_at: string;
  updated_at: string;
}
